name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifacts
        required: false
        default: dist
        type: string
    # secrets:
      # some-secret:
        # required: true
    outputs:
      result:
        description: The result of the deployment operation
        value: ${{ jobs.deploy.outputs.outcome }} # jobs object only in reusable workflows
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: Dummy Deploy
        run: echo "Deploying..."
      - name: Set result output
        run: echo "step-result=success" >> $GITHUB_OUTPUT
